name = "deepseek-agent"
main = "src/index.ts"
compatibility_date = "2025-02-13"

[[durable_objects.bindings]]
name = "CONVERSATIONS"
class_name = "FlowDO"

[[durable_objects.classes]]
name = "FlowDO"
script_name = "deepseek-agent"

[[d1_databases]]
binding = "PROJECT_FACTS_DB"
database_name = "flow-runs-db"
database_id = "ce8f2a2c-6e4b-4398-b73e-ba8f204f609a"